package com.example.csvccdshustbe.repository.otherVehicleTransportModule.impl;

import com.example.csvccdshustbe.repository.otherVehicleTransportModule.OtherVehicleTransportRepositoryCustom;

public class OtherVehicleTransportRepositoryImpl implements OtherVehicleTransportRepositoryCustom {
}
